management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
spring:
  servlet:
    multipart:
      max-file-size: 5MB
  cloud:
    vault:
      enabled: true
      host: 127.0.0.1
      token: 0000-0000-0000
      port: 8200
      scheme: http
      config:
        lifecycle:
          min-renewal: 1m
          expiry-threshold: 5m
      aws:
        enabled: true
        region: us-east-1
        role: demo_role
        backend: aws
        role-arn: arn:aws:iam::${AWS_ACCOUNT}:role/sts-app-role
        credential-type: federation_token
        access-key-property: cloud.aws.credentials.accessKey
        secret-key-property: cloud.aws.credentials.secretKey
        session-token-key-property: cloud.aws.credentials.sessionToken
        ttl: 3600s